export const actions = {
  quiz: {
    QUIZ_FETCHING: "QUIZ_DATA-FETCHING",
    QUIZ_FETCHED: "QUIZ_DATA-FETCHED",
    QUIZ_FETCH_ERROR: "QUIZ_DATA_FETCH_ERROR",
    QUIZ_EDITED: "QUIZ_ADMIN_EDITED",
    QUIZ_DELETED: "QUIZE_ADMIN_DELETED",
  },
};
